*** Variables ***

${ONE_TIME_REPORTS_ADD}  \#databutton-top .databutton:nth-child(1)
${ONE_TIME_REPORTS_STATIC_TEMPLATES}  \#cm3_link
${ONE_TIME_REPORTS_RAMSOMWARE_GROUPBY}  \#ID_OVL_COMP_RANSOMWARE
${ONE_TIME_REPORTS_TOP_USERS_WITH_THREATS}  \#ID_OVL_N_MostInfected_USERS
${ONE_TIME_REPORTS_TOP_ENDPOINTS_WITH_THREATS}  \#ID_OVL_N_MostInfected_ENDPOINTS
