from sqlalchemy import Column
from db.cm_session import cm_session, Base
from sqlalchemy.dialects.mssql import CHAR, DATETIME, INTEGER, NVARCHAR, VARCHAR


class TbCnCDetection(Base):
    __tablename__ = 'tb_CnCDetection'
    id = Column(INTEGER, primary_key=True, nullable=False)
    CMGuid = Column(CHAR(36))
    SLF_MsgType = Column(INTEGER)
    MsgLogID = Column(CHAR(36), nullable=False)
    SLF_ProductGUID = Column(CHAR(36), nullable=False)
    SLF_ProductID = Column(INTEGER)
    EI_ProductVersion = Column(VARCHAR(19))
    SLF_IPAddress = Column(VARCHAR(1024))
    LogReceivedTime = Column(DATETIME)
    LogReceivedUTCTime = Column(DATETIME)
    CLF_LogGenerationUTCTime = Column(DATETIME)
    SLF_ClientGUID = Column(CHAR(36))
    SLF_ClientHostName = Column(VARCHAR(128))
    SLF_ClientIP = Column(VARCHAR(256))
    SLF_DomainName = Column(NVARCHAR(64))
    SLF_PolicyName = Column(NVARCHAR(256))
    SLF_CCCA_DetectionSource = Column(INTEGER)
    SLF_CCCA_RiskLevel = Column(INTEGER)
    SLF_CCCA_DestinationFormat = Column(INTEGER)
    SLF_URL = Column(NVARCHAR(1024))
    SLF_CategoryIDs = Column(VARCHAR(128))
    SLF_CnCServerIP_Port = Column(VARCHAR(1024))
    SLF_InfectedClientIP_Port = Column(VARCHAR(1024))
    SLF_Sender = Column(NVARCHAR(254))
    SLF_Recipient = Column(NVARCHAR(254))
    SLF_Subject = Column(NVARCHAR(254))
    SLF_CnCServer_Country = Column(VARCHAR(128))
    SLF_CnCServer_City = Column(VARCHAR(128))
    SLF_InfectedClient_Country = Column(VARCHAR(128))
    SLF_InfectedClient_City = Column(VARCHAR(128))
    SLF_FirstSeen = Column(DATETIME)
    SLF_LastSeen = Column(DATETIME)
    CnCDestination = Column(NVARCHAR(2048))
    CnCInfectedClient = Column(NVARCHAR(2048))
    SLF_ActionResult = Column(INTEGER)
    SLF_Status = Column(INTEGER)
    MalwareFamilies = Column(VARCHAR(1024))
    CnCGroups = Column(VARCHAR(1024))
    ProcessName = Column(VARCHAR(2048))
    SLF_URLCorrelationKey = Column(VARCHAR(64))
    CLF_LogGenCMLocalTime = Column(DATETIME)
