from sqlalchemy import Column
from db.cm_session import cm_session, Base
from sqlalchemy.dialects.mssql import CHAR, DATETIME, IMAGE, INTEGER, NVARCHAR, VARCHAR


class TbChildSystemInfo(Base):
    __tablename__ = 'tb_ChildSystemInfo'
    SYS_SystemID = Column(CHAR(36), primary_key=True, nullable=False)
    CSI_ServerName = Column(NVARCHAR(256))
    CSI_BuildNo = Column(VARCHAR(24))
    CSI_ServicePackNo = Column(VARCHAR(24))
    CSI_HotfixNo = Column(VARCHAR(24))
    SYS_ASpyVersion = Column(VARCHAR(19))
    SYS_ASpyLastUpdateTime = Column(DATETIME)
    SYS_Registered = Column(INTEGER, nullable=False)
    SYS_SetupTime = Column(DATETIME)
    SYS_StartupTime = Column(DATETIME)
    SYS_ProductVersion = Column(NVARCHAR(33), nullable=False)
    SYS_VirusPatternVersion = Column(VARCHAR(19))
    SYS_VirusPtnLastUpdateTime = Column(DATETIME)
    SYS_SpamRuleVersion = Column(VARCHAR(19))
    SYS_SpamRuleLastUpdateTime = Column(DATETIME)
    SYS_CAVRule = Column(VARCHAR(19))
    SYS_CAVRuleLastUpdateTime = Column(DATETIME)
    SYS_PATTERN2 = Column(VARCHAR(19))
    SYS_PATTERN2LastUpdateTime = Column(DATETIME)
    SYS_MMPVersion = Column(VARCHAR(19))
    SYS_MMPVersionLastUpdateTime = Column(DATETIME)
    SYS_DCTVersion = Column(VARCHAR(19))
    SYS_DCTVersionLastUpdateTime = Column(DATETIME)
    SYS_VATVersion = Column(VARCHAR(19))
    SYS_VATVersionLastUpdateTime = Column(DATETIME)
    SYS_VIVersion = Column(VARCHAR(19))
    SYS_VIVersionLastUpdateTime = Column(DATETIME)
    SYS_SpywareVersion = Column(VARCHAR(19))
    SYS_SpywareLastUpdateTime = Column(DATETIME)
    SYS_CFWVersion = Column(VARCHAR(19))
    SYS_CFWLastUpdateTime = Column(DATETIME)
    SYS_SpyCleanUpVersion = Column(VARCHAR(19))
    SYS_SpyCleanUpLastUpdateTime = Column(DATETIME)
    CSI_OS_Name = Column(NVARCHAR(64))
    CSI_OS_Version = Column(VARCHAR(32))
    CSI_OS_SPVersion = Column(NVARCHAR(32))
    CSI_OS_Language = Column(NVARCHAR(32))
    CSI_OS_ContryCode = Column(VARCHAR(8))
    CSI_OS_MachineName = Column(NVARCHAR(64))
    CSI_IPAddressList = Column(VARCHAR(1024))
    CSI_MACAddressList = Column(VARCHAR(256))
    CSI_DomainName = Column(NVARCHAR(64))
    CSI_WebServer_Port = Column(INTEGER)
    CSI_WebServer_Https_Port = Column(INTEGER)
    CSI_SecurityLevel = Column(INTEGER)
    CSI_ExtraInfo1 = Column(INTEGER)
    CSI_ExtraInfo2 = Column(VARCHAR(256))
    CSI_ExtraInfo3 = Column(NVARCHAR(128))
    CSI_ExtraInfo4 = Column(IMAGE)
