from sqlalchemy import Column
from db.cm_session import cm_session, Base
from sqlalchemy.dialects.mssql import BINARY, CHAR, DATETIME, INTEGER, NVARCHAR, SMALLINT, VARCHAR


class Tbcascadingjournalentitydata(Base):
    __tablename__ = 'tb_cascadingjournalentitydata'
    id = Column(INTEGER, primary_key=True, nullable=False)
    Guid = Column(CHAR(36))
    AgentGuid = Column(CHAR(36))
    ParentGuid = Column(CHAR(36))
    CMGuid = Column(CHAR(36))
    ProductType = Column(INTEGER)
    ProductVersion = Column(VARCHAR(19))
    MenuVersion = Column(VARCHAR(8))
    ProductLanguage = Column(INTEGER)
    BuildNumber = Column(VARCHAR(24))
    Status = Column(INTEGER)
    IconIndex = Column(SMALLINT)
    ConfigureURL = Column(VARCHAR(509))
    LastRegistrationTime = Column(DATETIME)
    LastLogonTime = Column(DATETIME)
    ServicePack = Column(VARCHAR(32))
    EntityType = Column(INTEGER)
    SLF_UpdateAgentType = Column(INTEGER)
    SLF_LastStartupTime = Column(DATETIME)
    OS_Name = Column(NVARCHAR(64))
    OS_Version = Column(VARCHAR(32))
    OS_ServicePackVersion = Column(VARCHAR(32))
    OS_Language = Column(INTEGER)
    OS_CountryCode = Column(VARCHAR(32))
    CpuType = Column(SMALLINT)
    ComputerName = Column(NVARCHAR(64))
    IPAddressList = Column(VARCHAR(2048))
    MACAddressList = Column(VARCHAR(2048))
    DomainName = Column(NVARCHAR(64))
    FQDN = Column(VARCHAR(80))
    TimeZone = Column(INTEGER)
    DayLightSaving = Column(BINARY(40))
    AgentType = Column(SMALLINT)
    AgentStatus = Column(INTEGER)
    AgentToken = Column(VARCHAR(1024))
    PollingFrequency = Column(INTEGER)
    HeartbeatFrequency = Column(INTEGER)
    LastHeartbeatTime = Column(INTEGER)
    Offhour = Column(BINARY(12))
    AgentVersion = Column(VARCHAR(32))
    AgentBuild = Column(VARCHAR(32))
    ClientTreePath = Column(NVARCHAR(1000))
    CloudScanMode = Column(SMALLINT)
    CloudScanMethod = Column(SMALLINT)
    SourceHashes = Column(VARCHAR(1024))
    LogReceivedTime = Column(DATETIME)
    GroupName = Column(VARCHAR(64))
    ADObjectGuid = Column(CHAR(36))
    OSType = Column(VARCHAR(16))
    PlatformType = Column(VARCHAR(16))
    MachineID = Column(CHAR(36))
    UserGuid = Column(CHAR(36))
    UserAccount = Column(NVARCHAR(32))
    UserDomain = Column(NVARCHAR(256))
    UserMail = Column(NVARCHAR(450))
    SystemModel = Column(SMALLINT)
    AD_DomainName = Column(NVARCHAR(64))
