from sqlalchemy import Column
from db.cm_session import cm_session, Base
from sqlalchemy.dialects.mssql import CHAR, DATETIME, INTEGER, NVARCHAR, SMALLINT, VARCHAR


class TbLogIntrusionPrevention(Base):
    __tablename__ = 'tb_LogIntrusionPrevention'
    id = Column(INTEGER, primary_key=True, nullable=False)
    MsgLogID = Column(CHAR(36), nullable=False)
    MsgLogType = Column(SMALLINT, nullable=False)
    CMGuid = Column(CHAR(36), nullable=False)
    ProductGUID = Column(CHAR(36), nullable=False)
    ProductID = Column(INTEGER, nullable=False)
    LogVersion = Column(SMALLINT, nullable=False)
    LogMinorVersion = Column(SMALLINT, nullable=False)
    LogReceivedUTCTime = Column(DATETIME, nullable=False)
    LogReceivedTime = Column(DATETIME, nullable=False)
    LogReceivedTimeZone = Column(INTEGER, nullable=False)
    LogGenUTCDatetime = Column(DATETIME, nullable=False)
    LogGenLocalDatetime = Column(DATETIME, nullable=False)
    TimeZoneInMins = Column(SMALLINT, nullable=False)
    DaylightSavingInMins = Column(SMALLINT, nullable=False)
    ComputerName = Column(NVARCHAR(128), nullable=False)
    ClientGUID = Column(CHAR(36))
    SourceIP = Column(VARCHAR(256))
    SourceMAC = Column(VARCHAR(17))
    SourcePort = Column(INTEGER)
    DestinationIP = Column(VARCHAR(256))
    DestinationMAC = Column(VARCHAR(17))
    DestinationPort = Column(INTEGER)
    InterestedIP = Column(VARCHAR(256), nullable=False)
    InterestedMAC = Column(VARCHAR(17))
    PeerIP = Column(VARCHAR(256))
    Mode = Column(SMALLINT)
    Action = Column(SMALLINT)
    Direction = Column(SMALLINT)
    Rank = Column(INTEGER)
    SeverityCode = Column(INTEGER)
    AssetValue = Column(INTEGER)
    FilterSeverityValue = Column(INTEGER)
    Protocol = Column(SMALLINT)
    ConnectionTypeID = Column(INTEGER)
    ConnectionType = Column(NVARCHAR(256))
    RuleID = Column(INTEGER)
    RuleContent = Column(NVARCHAR(256))
    FilterStatus = Column(NVARCHAR(256))
    Note = Column(NVARCHAR(256))
    SLF_Is_CCCA_Detection = Column(INTEGER)
    SLF_CCCA_DetectionSource = Column(INTEGER)
    SLF_CCCA_RiskLevel = Column(INTEGER)
    AggregatedUTCDatetime = Column(DATETIME)
    AggregatedLocalDatetime = Column(DATETIME)
    AggregatedCount = Column(INTEGER)
    CE_FilterID = Column(VARCHAR(35))
    CLF_LogGenCMLocalTime = Column(DATETIME)
