from sqlalchemy import Column
from db.cm_session import cm_session, Base
from sqlalchemy.dialects.mssql import BIGINT, CHAR, DATETIME, INTEGER, NVARCHAR, UNIQUEIDENTIFIER, VARCHAR


class TbLogDataLossPreventionCasStorage(Base):
    __tablename__ = 'tb_LogDataLossPrevention_CasStorage'
    CMGuid = Column(CHAR(36))
    id = Column(INTEGER, primary_key=True, nullable=False)
    MsgLogID = Column(CHAR(36), nullable=False)
    LogReceivedTime = Column(DATETIME)
    LogReceivedUTCTime = Column(DATETIME)
    LogReceivedTimeZone = Column(VARCHAR(10))
    SLF_ProductGUID = Column(CHAR(36), nullable=False)
    SLF_MsgType = Column(INTEGER)
    SLF_ClientGUID = Column(CHAR(36))
    SLF_ProductID = Column(INTEGER)
    SLF_LogVersion = Column(INTEGER)
    SLF_LogMinorVersion = Column(INTEGER)
    SLF_ComputerName = Column(NVARCHAR(128))
    SLF_LogGenUTCDatetime = Column(DATETIME)
    SLF_LogGenLocalDatetime = Column(DATETIME)
    SLF_TimeZoneInMins = Column(INTEGER)
    SLF_DaylightSavingInMins = Column(INTEGER)
    SLF_IPAddress = Column(VARCHAR(32))
    SLF_MACAddressList = Column(VARCHAR(2048))
    SLF_InfectedHostName = Column(NVARCHAR(64))
    SLF_UserName = Column(NVARCHAR(64))
    SLF_Recipient = Column(NVARCHAR(1024))
    SLF_Subject = Column(NVARCHAR(1024))
    SLF_FilePath = Column(NVARCHAR(256))
    SLF_Filename = Column(NVARCHAR(256))
    SLF_SourcePort = Column(INTEGER)
    SLF_DestinationIP = Column(VARCHAR(256))
    SLF_DestinationPort = Column(INTEGER)
    SLF_UserDomain = Column(NVARCHAR(256))
    SLF_ComputerDomain = Column(NVARCHAR(256))
    SLF_UserDepartment = Column(NVARCHAR(256))
    SLF_Sender = Column(NVARCHAR(256))
    SLF_URL = Column(VARCHAR(1024))
    SLF_FTPUserName = Column(NVARCHAR(256))
    SLF_ProcessName = Column(NVARCHAR(256))
    SLF_OfflineFlag = Column(INTEGER)
    SLF_ContentType = Column(INTEGER)
    SLF_ForensicCaptured = Column(INTEGER)
    SLF_ForensicFilePath = Column(NVARCHAR(260))
    SLF_MatchedContent = Column(NVARCHAR(128))
    SLF_Channel = Column(INTEGER)
    PolicyID = Column(UNIQUEIDENTIFIER)
    SLF_UserGuid = Column(CHAR(36))
    ViolationID = Column(NVARCHAR(36))
    ForensicDataFileHash = Column(VARCHAR(128))
    RuleNames = Column(NVARCHAR)
    TemplateNames = Column(NVARCHAR)
    Actions = Column(NVARCHAR)
    Reason = Column(NVARCHAR(1024))
    SeverityCode = Column(INTEGER)
    Status = Column(INTEGER)
    Description = Column(NVARCHAR(1024))
    FileDownloadRetCode = Column(INTEGER)
    Destination = Column(NVARCHAR(1024))
    SLF_FileSize = Column(BIGINT)
