from sqlalchemy import Column
from db.cm_session import cm_session, Base
from sqlalchemy.dialects.mssql import BIGINT, CHAR, DATETIME, INTEGER, NVARCHAR, VARCHAR


class TbLogIP(Base):
    __tablename__ = 'tb_LogIP'
    CMGuid = Column(CHAR(36))
    id = Column(INTEGER, nullable=False)
    BOTCmd = Column(VARCHAR(512))
    BOTUrl = Column(NVARCHAR(512))
    ChannelName = Column(NVARCHAR(200))
    ConfidenceLevel = Column(INTEGER)
    DestIP = Column(VARCHAR(256))
    DestMAC = Column(VARCHAR(17))
    DestPort = Column(INTEGER)
    DomainName = Column(VARCHAR(256))
    HostName = Column(VARCHAR(256))
    Nickname = Column(VARCHAR(256))
    SourceIP = Column(VARCHAR(256))
    SourceMAC = Column(VARCHAR(17))
    SourcePort = Column(INTEGER)
    URL = Column(NVARCHAR(1024))
    UserAgent = Column(VARCHAR(256))
    UserName = Column(NVARCHAR(64))
    SrcGroupName = Column(NVARCHAR(128))
    SrcZone = Column(INTEGER)
    DstGroupName = Column(NVARCHAR(128))
    DstZone = Column(INTEGER)
    Score = Column(INTEGER)
    MsgLogID = Column(CHAR(36))
    SeqID = Column(BIGINT, primary_key=True, nullable=False)
    SrcUserName = Column(NVARCHAR(256))
    DestUserName = Column(NVARCHAR(256))
    SrcHostname = Column(NVARCHAR(512))
    DestHostname = Column(NVARCHAR(512))
    ProtocolHostname = Column(NVARCHAR(256))
    CategoryIDList = Column(NVARCHAR(512))
    SrcUserName2 = Column(NVARCHAR(256))
    SrcUserName3 = Column(NVARCHAR(256))
    SrcUserLoginTime1 = Column(DATETIME)
    SrcUserLoginTime2 = Column(DATETIME)
    SrcUserLoginTime3 = Column(DATETIME)
    DestUsername2 = Column(NVARCHAR(256))
    DestUsername3 = Column(NVARCHAR(256))
    DestUserLoginTime1 = Column(DATETIME)
    DestUserLoginTime2 = Column(DATETIME)
    DestUserLoginTime3 = Column(DATETIME)
    SrcOS = Column(NVARCHAR(255))
    DestOS = Column(NVARCHAR(255))
    SLF_URLCorrelationKey = Column(VARCHAR(64))
    Is_CCCA_Detection = Column(INTEGER)
    HTTPReferer = Column(NVARCHAR(2048))
    CE_FilterID = Column(VARCHAR(35))
