from sqlalchemy import Column
from db.cm_session import cm_session, Base
from sqlalchemy.dialects.mssql import BIGINT, BIT, CHAR, DATETIME, INTEGER, NVARCHAR


class TbMDRTaskList(Base):
    __tablename__ = 'tb_MDR_TaskList'
    id = Column(BIGINT, primary_key=True, nullable=False)
    TaskID = Column(CHAR(36))
    TaskType = Column(NVARCHAR(64))
    CreateTime = Column(DATETIME)
    PendingExpirationTime = Column(DATETIME)
    Status = Column(INTEGER)
    Finished = Column(BIT)
    TargetType = Column(INTEGER)
    Targets = Column(NVARCHAR)
    TargetCount = Column(INTEGER)
    TaskPayload = Column(NVARCHAR)
    Commander = Column(NVARCHAR(1024))
    Description = Column(NVARCHAR(1024))
    ExtraInfo = Column(NVARCHAR)
    LastUpdateTime = Column(DATETIME)
    TaskReceivedTime = Column(DATETIME)
    AutoGenerated = Column(BIT)
