from sqlalchemy import Column
from db.cm_session import cm_session, Base
from sqlalchemy.dialects.mssql import CHAR, DATETIME, INTEGER, NVARCHAR, VARCHAR


class TbMachineLearningDetectionLog(Base):
    __tablename__ = 'tb_MachineLearning_Detection_Log'
    id = Column(INTEGER, primary_key=True, nullable=False)
    MsgLogID = Column(CHAR(36), nullable=False)
    CMGuid = Column(CHAR(36))
    SLF_MsgType = Column(INTEGER)
    SLF_ProductGUID = Column(CHAR(36), nullable=False)
    SLF_ClientGUID = Column(CHAR(36))
    SLF_ProductID = Column(INTEGER)
    SLF_LogVersion = Column(INTEGER)
    SLF_LogMinorVersion = Column(INTEGER)
    SLF_LogGenUTCDatetime = Column(DATETIME)
    SLF_LogGenLocalDatetime = Column(DATETIME)
    SLF_TimeZoneInMins = Column(INTEGER)
    SLF_DaylightSavingInMins = Column(INTEGER)
    LogReceivedTime = Column(DATETIME)
    LogReceivedUTCTime = Column(DATETIME)
    LogReceivedTimeZone = Column(INTEGER)
    SLF_ComputerName = Column(NVARCHAR(128))
    SLF_IPAddress = Column(VARCHAR(32))
    SLF_Action = Column(INTEGER)
    SLF_ActionResult = Column(INTEGER)
    SLF_FilePath = Column(NVARCHAR(256))
    SLF_FileSHA1 = Column(VARCHAR(64), nullable=False)
    SLF_Filename = Column(NVARCHAR(256))
    SLF_FileCreationDate = Column(DATETIME)
    SLF_FileDescription = Column(NVARCHAR(256))
    SLF_FileSize = Column(INTEGER)
    SLF_TrueFileType = Column(VARCHAR(16))
    SLF_Protocol = Column(INTEGER)
    SLF_ProtocolLocation = Column(NVARCHAR(512))
    SLF_InfectionSource = Column(NVARCHAR(128))
    SLF_DetectionType = Column(INTEGER)
    SLF_ParentProcess = Column(NVARCHAR(256))
    SLF_ProcessOwner = Column(NVARCHAR(32))
    SLF_ProcessCommandLine = Column(NVARCHAR(512))
    SLF_Confidence = Column(INTEGER)
    SLF_ThreatType = Column(NVARCHAR(64))
    SLF_DetectionName = Column(NVARCHAR(64))
    SLF_FileSignerInfo = Column(NVARCHAR(128))
    SLF_Subject = Column(NVARCHAR(512))
    SLF_DeliverTime = Column(NVARCHAR(30))
    SLF_MailID = Column(NVARCHAR(256))
    SLF_Sender = Column(NVARCHAR(512))
    SLF_Recipient = Column(NVARCHAR(512))
    SLF_CloudStorage = Column(INTEGER)
    CE_FilterID = Column(VARCHAR(35))
    CLF_LogGenCMLocalTime = Column(DATETIME)
