from sqlalchemy import Column
from db.cm_session import cm_session, Base
from sqlalchemy.dialects.mssql import CHAR, DATETIME, INTEGER, NVARCHAR, VARCHAR


class TbPersonalFirewallLog(Base):
    __tablename__ = 'tb_PersonalFirewallLog'
    id = Column(INTEGER, primary_key=True, nullable=False)
    MsgLogID = Column(CHAR(36), nullable=False)
    MsgLogType = Column(INTEGER)
    ProductGUID = Column(CHAR(36))
    ClientGUID = Column(CHAR(36))
    ProductID = Column(INTEGER)
    LogVersion = Column(INTEGER)
    LogMinorVersion = Column(INTEGER)
    ComputerName = Column(NVARCHAR(128))
    LogGenUTCDatetime = Column(DATETIME)
    LogGenLocalDatetime = Column(DATETIME)
    TimeZoneInMins = Column(INTEGER)
    DaylightSavingInMins = Column(INTEGER)
    RedAlertID = Column(CHAR(36))
    Direction = Column(INTEGER)
    Protocol = Column(INTEGER)
    SourceIP = Column(VARCHAR(256))
    SourcePort = Column(INTEGER)
    DestinationIP = Column(VARCHAR(256))
    DestinationPort = Column(INTEGER)
    EventType = Column(INTEGER)
    SubType = Column(INTEGER)
    RiskLevel = Column(INTEGER)
    PolicyName = Column(NVARCHAR(256))
    RuleID = Column(NVARCHAR(256))
    Description = Column(NVARCHAR(1024))
    ProcessName = Column(NVARCHAR(256))
    ApplicationName = Column(NVARCHAR(256))
    VirusName = Column(NVARCHAR(256))
    ActionResult = Column(INTEGER)
    LogReceivedTime = Column(DATETIME)
    LogReceivedUTCTime = Column(DATETIME)
    AggregatedUTCDatetime = Column(DATETIME)
    AggregatedLocalDatetime = Column(DATETIME)
    AggregatedCount = Column(INTEGER)
    SLF_Is_CCCA_Detection = Column(INTEGER)
    SLF_CCCA_DetectionSource = Column(INTEGER)
    SLF_CCCA_RiskLevel = Column(INTEGER)
    SLF_HostName = Column(VARCHAR(128))
    CE_FilterID = Column(VARCHAR(35))
    CLF_LogGenCMLocalTime = Column(DATETIME)
