from sqlalchemy import Column
from db.cm_session import cm_session, Base
from sqlalchemy.dialects.mssql import CHAR, DATETIME, IMAGE, INTEGER, NVARCHAR, VARCHAR


class TbRegTmpEntityInfo(Base):
    __tablename__ = 'tb_RegTmp_EntityInfo'
    id = Column(INTEGER, primary_key=True, nullable=False)
    EI_EntityID = Column(CHAR(36), nullable=False)
    EI_AgentID = Column(CHAR(36), nullable=False)
    EI_ParentID = Column(CHAR(36), nullable=False)
    EI_ManagerID = Column(CHAR(36), nullable=False)
    EI_State = Column(INTEGER)
    EI_Type = Column(INTEGER)
    EI_SerialNumber = Column(VARCHAR(60))
    EI_ProductType = Column(INTEGER, nullable=False)
    EI_ProductVersion = Column(VARCHAR(19))
    EI_ProductLanguage = Column(INTEGER)
    EI_SetupTime = Column(DATETIME)
    EI_LastRegistrationTime = Column(DATETIME)
    EI_LastLogonTime = Column(DATETIME)
    EI_LastLogoffTime = Column(DATETIME)
    EI_CacheToken = Column(VARCHAR(256))
    EI_UpdateSourceID = Column(CHAR(36))
    EI_MenuVersion = Column(VARCHAR(8))
    EI_ProductBuildNumber = Column(VARCHAR(24))
    EI_LastStartupTime = Column(DATETIME)
    EI_PatternNumber = Column(VARCHAR(19))
    EI_PatternLastUpdateTime = Column(DATETIME)
    EI_SpamRuleNumber = Column(VARCHAR(8))
    EI_SpamRuleLastUpdateTime = Column(DATETIME)
    EI_SpamRuleFilename1 = Column(VARCHAR(16))
    EI_SpamRule1LastUpdateTime = Column(DATETIME)
    EI_SpamRuleFilename2 = Column(VARCHAR(16))
    EI_SpamRule2LastUpdateTime = Column(DATETIME)
    EI_DCTNumber = Column(VARCHAR(19))
    EI_DCTLastUpdateTime = Column(DATETIME)
    EI_OS_Name = Column(NVARCHAR(128))
    EI_OS_Version = Column(VARCHAR(64))
    EI_OS_SPVersion = Column(VARCHAR(32))
    EI_OS_Language = Column(INTEGER)
    EI_OS_ContryCode = Column(VARCHAR(8))
    EI_OS_MachineName = Column(NVARCHAR(64))
    EI_IPAddressList = Column(VARCHAR(1024))
    EI_MACAddressList = Column(VARCHAR(256))
    EI_DomainName = Column(NVARCHAR(64))
    EI_PrivateAttribute = Column(IMAGE)
    EI_Timezone = Column(VARCHAR(8))
    EI_LastNotifyTime = Column(DATETIME)
    EI_AgentVersion = Column(VARCHAR(64))
    EI_CAVRule = Column(VARCHAR(19))
    EI_CAVRuleUpdateTime = Column(DATETIME)
    EI_Pattern2Version = Column(VARCHAR(19))
    EI_Pattern2VersionUpdateTime = Column(DATETIME)
    EI_VATVersion = Column(VARCHAR(19))
    EI_VATVersionUpdateTime = Column(DATETIME)
    EI_VIVersion = Column(VARCHAR(19))
    EI_VIVersionUpdateTime = Column(DATETIME)
    EI_SpywareVersion = Column(VARCHAR(19))
    EI_SpywareLastUpdateTime = Column(DATETIME)
    EI_CFWVersion = Column(VARCHAR(19))
    EI_CFWLastUpdateTime = Column(DATETIME)
    EI_SpyCleanUpVersion = Column(VARCHAR(19))
    EI_SpyCleanUpLastUpdateTime = Column(DATETIME)
    EI_GroupName = Column(NVARCHAR(64))
    EI_ASpyVersion = Column(VARCHAR(19))
    EI_ASpyLastUpdateTime = Column(DATETIME)
    EI_AgentBuild = Column(INTEGER)
