from sqlalchemy import Column
from db.cm_session import cm_session, Base
from sqlalchemy.dialects.mssql import BIGINT, BIT, CHAR, DATETIME, UNIQUEIDENTIFIER, VARCHAR


class TbSystemInfo(Base):
    __tablename__ = 'tb_SystemInfo'
    SYS_SystemID = Column(CHAR(36), primary_key=True, nullable=False)
    SYS_SystemID_Guid = Column(UNIQUEIDENTIFIER)
    SYS_Registered = Column(BIT, nullable=False)
    SYS_SetupTime = Column(DATETIME)
    SYS_StartupTime = Column(DATETIME)
    SYS_ProductVersion = Column(VARCHAR(19), nullable=False)
    SYS_VirusPatternVersion = Column(VARCHAR(19))
    SYS_VirusPtnLastUpdateTime = Column(DATETIME)
    SYS_SpamRuleVersion = Column(VARCHAR(19))
    SYS_SpamRuleLastUpdateTime = Column(DATETIME)
    SYS_MMPVersion = Column(VARCHAR(19))
    SYS_MMPVersionLastUpdateTime = Column(DATETIME)
    SYS_DCTVersion = Column(VARCHAR(19))
    SYS_DCTVersionLastUpdateTime = Column(DATETIME)
    SYS_PATTERN2 = Column(VARCHAR(19))
    SYS_PATTERN2LastUpdateTime = Column(DATETIME)
    SYS_CAVRule = Column(VARCHAR(19))
    SYS_CAVRuleLastUpdateTime = Column(DATETIME)
    SYS_VATVersion = Column(VARCHAR(19))
    SYS_VATVersionLastUpdateTime = Column(DATETIME)
    SYS_VIVersion = Column(VARCHAR(19))
    SYS_VIVersionLastUpdateTime = Column(DATETIME)
    SYS_SpywareVersion = Column(VARCHAR(19))
    SYS_SpywareLastUpdateTime = Column(DATETIME)
    SYS_CFWVersion = Column(VARCHAR(19))
    SYS_CFWLastUpdateTime = Column(DATETIME)
    SYS_SpyCleanUpVersion = Column(VARCHAR(19))
    SYS_SpyCleanUpLastUpdateTime = Column(DATETIME)
    SYS_ASpyVersion = Column(VARCHAR(19))
    SYS_ASpyLastUpdateTime = Column(DATETIME)
    ET_VSAPI32_95 = Column(VARCHAR(19))
    ET_VSAPI32_VXD = Column(VARCHAR(19))
    ET_VSAPI32_NT_I386 = Column(VARCHAR(19))
    ET_VSAPI32_NT_ALPHA = Column(VARCHAR(19))
    ET_VSAPI32_NT_KD = Column(VARCHAR(19))
    ET_VSAPI32_NLM = Column(VARCHAR(19))
    ET_VSAPI32_OS2 = Column(VARCHAR(19))
    ET_VSAPI32_DOS4G = Column(VARCHAR(19))
    ET_VSAPI32_SOLARIS = Column(VARCHAR(19))
    ET_VSAPI32_SOLARIS_X86 = Column(VARCHAR(19))
    ET_VSAPI32_HPUX = Column(VARCHAR(19))
    ET_VSAPI32_AIX = Column(VARCHAR(19))
    ET_VSAPI32_SOLARIS_SPARC = Column(VARCHAR(19))
    ET_VSAPI32_LINUX_X86 = Column(VARCHAR(19))
    ET_PREVSAPI32_95 = Column(VARCHAR(19))
    ET_PREVSAPI32_NT = Column(VARCHAR(19))
    ET_PREVSAPI16 = Column(VARCHAR(19))
    ET_VSAPI_ALL = Column(VARCHAR(19))
    SYS_ProductBuild = Column(VARCHAR(19))
    SYS_HotfixNumber = Column(VARCHAR(19))
    SYS_SOExceptionChangeKey = Column(BIGINT)
    GlobalRetroScanUserID = Column(VARCHAR(64))
    GlobalRetroScanUserKey = Column(VARCHAR(256))
    MDR_SenderGUID = Column(CHAR(36))

    @classmethod
    def get_CM_guid(cls):
        return cm_session.query(cls).first().SYS_SystemID
