from sqlalchemy import Column
from db.cm_session import cm_session, Base
from sqlalchemy.dialects.mssql import BIT, CHAR, DATETIME, IMAGE, INTEGER, NVARCHAR, VARCHAR


class TbVASHistoryStatus(Base):
    __tablename__ = 'tb_VASHistoryStatus'
    id = Column(INTEGER, primary_key=True, nullable=False)
    MsgLogID = Column(CHAR(36), nullable=False)
    CLF_MsgLogType = Column(INTEGER)
    CLF_EntityID = Column(CHAR(36))
    CLF_LogVersion = Column(INTEGER)
    CLF_LogMinorVersion = Column(VARCHAR(10))
    CLF_ManagerID = Column(CHAR(36))
    CLF_ComputerName = Column(NVARCHAR(128))
    CLF_ProductType = Column(INTEGER)
    CLF_ProductVersion = Column(VARCHAR(21))
    CLF_ProductPlatformCode = Column(INTEGER)
    CLF_ProductLanguageCode = Column(INTEGER)
    CLF_ServerityCode = Column(INTEGER)
    CLF_ComponentCode = Column(INTEGER)
    CLF_LogReplicatedFlag = Column(BIT)
    CLF_LogGenerationTime = Column(DATETIME)
    CLF_LogGenerationTimeZone = Column(VARCHAR(10))
    CLF_LogReceivedTime = Column(DATETIME)
    CLF_LogReceivedTimeZone = Column(VARCHAR(10))
    CLF_IsDayLightSaving = Column(INTEGER)
    CLF_ReasonCode = Column(VARCHAR(64))
    CLF_ReasonCodeSource = Column(INTEGER)
    CLF_ReasonCodeSymbol = Column(VARCHAR(64))
    CLF_ReasonCodeDescription = Column(NVARCHAR(1024))
    CLF_RedAlertID = Column(VARCHAR(36))
    VAS_JobID = Column(INTEGER)
    VAS_TaskID = Column(INTEGER)
    VAS_Action = Column(INTEGER)
    VAS_Restricted = Column(INTEGER)
    VAS_Status = Column(INTEGER)
    VAS_Description = Column(INTEGER)
    VAS_DomainName = Column(NVARCHAR(16))
    VAS_IPAddress = Column(VARCHAR(256))
    VAS_TaskName = Column(NVARCHAR(64))
    VAS_EngineVersion = Column(VARCHAR(19))
    VAS_TemplateNumber = Column(VARCHAR(19))
    VAS_VulnerabilityNames = Column(IMAGE)
    VAS_PotentialVirus = Column(IMAGE)
