from sqlalchemy import Column
from db.cm_session import cm_session, Base
from sqlalchemy.dialects.mssql import BIT, CHAR, DATETIME, INTEGER, NVARCHAR, VARCHAR


class TbWebSecurityLog(Base):
    __tablename__ = 'tb_WebSecurityLog'
    id = Column(INTEGER, primary_key=True, nullable=False)
    MsgLogID = Column(CHAR(36))
    CLF_MsgLogType = Column(INTEGER)
    CLF_EntityID = Column(CHAR(36))
    CLF_LogVersion = Column(INTEGER)
    CLF_LogMinorVersion = Column(VARCHAR(10))
    CLF_ManagerID = Column(CHAR(36))
    CLF_ComputerName = Column(NVARCHAR(128))
    CLF_ProductType = Column(INTEGER)
    CLF_ProductVersion = Column(VARCHAR(21))
    CLF_ProductPlatformCode = Column(INTEGER)
    CLF_ProductLanguageCode = Column(INTEGER)
    CLF_ServerityCode = Column(INTEGER)
    CLF_ComponentCode = Column(INTEGER)
    CLF_LogReplicatedFlag = Column(BIT)
    CLF_LogGenerationTime = Column(DATETIME)
    CLF_LogGenerationTimeZone = Column(VARCHAR(10))
    CLF_LogReceivedTime = Column(DATETIME)
    CLF_LogReceivedUTCTime = Column(DATETIME)
    CLF_LogReceivedTimeZone = Column(VARCHAR(10))
    CLF_IsDayLightSaving = Column(INTEGER)
    CLF_ReasonCode = Column(VARCHAR(64))
    CLF_ReasonCodeSource = Column(INTEGER)
    CLF_ReasonCodeSymbol = Column(VARCHAR(64))
    CLF_ReasonCodeDescription = Column(NVARCHAR(1024))
    CLF_RedAlertID = Column(VARCHAR(36))
    SLF_ObjectNameURL = Column(NVARCHAR(1024))
    SLF_ClientIP = Column(VARCHAR(256))
    SLF_ClientHostName = Column(VARCHAR(128))
    SLF_FileName = Column(NVARCHAR(254))
    SLF_BlockingType = Column(INTEGER)
    SLF_BlockingRule = Column(NVARCHAR(1024))
    SLF_Direction = Column(INTEGER)
    SLF_Protocol = Column(INTEGER)
    SLF_ServerIP = Column(VARCHAR(256))
    SLF_ServerPort = Column(INTEGER)
    SLF_ClientGuid = Column(CHAR(36))
    SLF_LoginUser = Column(NVARCHAR(128))
    SLF_UserAgentType = Column(INTEGER)
    SLF_DetectionType = Column(INTEGER)
    SLF_SeverityLevel = Column(INTEGER)
    SLF_CredibilityLevel = Column(INTEGER)
    SLF_RatingThreshold = Column(INTEGER)
    SLF_ReputationScore = Column(INTEGER)
    SLF_PolicyName = Column(NVARCHAR(256))
    SLF_Action = Column(INTEGER)
    SLF_Reason = Column(NVARCHAR(1024))
    AggregatedUTCDatetime = Column(DATETIME)
    AggregatedLocalDatetime = Column(DATETIME)
    AggregatedCount = Column(INTEGER)
    UserGroupName = Column(NVARCHAR(128))
    SLF_Is_CCCA_Detection = Column(INTEGER)
    SLF_CCCA_DetectionSource = Column(INTEGER)
    SLF_CCCA_RiskLevel = Column(INTEGER)
    SLF_CCCA_Destination = Column(VARCHAR(2048))
    SLF_CCCA_DestinationFormat = Column(INTEGER)
    SLF_ProcessName = Column(NVARCHAR(256))
    SLF_UserMail = Column(NVARCHAR(450))
    SLF_URLCorrelationKey = Column(VARCHAR(64))
    CE_FilterID = Column(VARCHAR(35))
    CLF_LogGenCMLocalTime = Column(DATETIME)
