*** Variables ***
# Managed Products
${DIRTRIBUTION_MANAGED_PRODUCTS_TAB}  btn_productsTab
${DIRTRIBUTION_MANAGED_PRODUCTS_ENABLE_CHECKBOX}  chkReputationListDeployment
${DIRTRIBUTION_MANAGED_PRODUCTS_SAVE_BUTTON}  btnProductSave
${DIRTRIBUTION_MANAGED_PRODUCTS_CANCEL_BUTTON}  btnProductCancel
${DIRTRIBUTION_MANAGED_PRODUCTS_SYNCNOW_BUTTON}  btnProductSyncNow
${DIRTRIBUTION_MANAGED_PRODUCTS_SERVICE_URL_INPUT}  txtServiceURL
${DIRTRIBUTION_MANAGED_PRODUCTS_APIKEY_LABEL}  txtAPIKey

# Tipping Points
${DIRTRIBUTION_TP_TAB}  btn_TippingPointTab
${DIRTRIBUTION_TP_ENABLE_CHECKBOX}  chkSendToTippingPoint
${DIRTRIBUTION_TP_SERVER_ADDRESS_INPUT}  txtHPServerName
${DIRTRIBUTION_TP_USERNAME_INPUT}  txtUserName
${DIRTRIBUTION_TP_PASSWORD_INPUT}  txtPassword
${DIRTRIBUTION_TP_HIGH_ONLY_RADIO}  radRiskRatingHighOnly
${DIRTRIBUTION_TP_HIGH_AND_MEDIUM_RADIO}  radRiskRatingHighandMedium
${DIRTRIBUTION_TP_ALL_RADIO}  radRiskRatingAll
${DIRTRIBUTION_TP_SAVE_BUTTON}  btnTPSave
${DIRTRIBUTION_TP_CANCEL_BUTTON}  btnTPCancel
${DIRTRIBUTION_TP_SYNCNOW_BUTTON}  btnTPSyncNow
${DIRTRIBUTION_TP_LAST_UPDATE_TIME}  Label_LastUpdateTimeValue

# Hub CM
${DIRTRIBUTION_HUB_CM_TAB}  btn_hubTab
${DIRTRIBUTION_HUB_CM_SERVICE_URL_INPUT}  txtHubServerURL
${DIRTRIBUTION_HUB_CM_APIKEY_INPUT}  txtHubAPIkey
${DIRTRIBUTION_HUB_CM_SYNC_FREQUENCY_DROPDOWN}  selectHubSyncPeriod
${DIRTRIBUTION_HUB_CM_REGISTER_BUTTON}  btnHubRegister
${DIRTRIBUTION_HUB_CM_UNREGISTER_BUTTON}  btnHubUnregister
${DIRTRIBUTION_HUB_CM_SAVE_BUTTON}  btnHubSave
${DIRTRIBUTION_HUB_CM_CNACEL_BUTTON}  btnHubCancel
